#### 第49节：手动抛出异常
##### 手动抛出异常
    throw exception

exception 是throwable类的子类，而且只能抛出一个异常

try……catch……finally可以嵌套使用。